### ISSUE TITLE
Add function to get team info

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#10]
A function that returns basic information about the team, such as:

- Team name
- Team headquarters
- Team principal/chief
- Chassis name
- Number of fastest laps/ pole positions/ WCCs

**Comment by ThejasBK** [comment]
I can do this Alec-kr
Could you assign it to me?

**Comment by alec-kr** [comment]
Hey there. This issue is on my backlog since I have no idea how we can acquire the data needed for the function, such as the chassis name and team principal name.

If you have an idea on how this data can be acquired, I will be glad to assign the issue to you :)

**Comment by alec-kr** [comment]
Closing issue since the Ergast API does not provide this data.
