### ISSUE TITLE
Refactoring modules

### ISSUE THREAD

**Issue by irahorecka** [alec-kr/F1PyStats#11]
Hello - I’m wondering if I may contribute by refactoring some of your modules? I would like to make some functions more concise, and I’ll do my best to preserve the current module API.

**Comment by alec-kr** [comment]
Hello. Refactoring the modules sounds like a great idea! Feel free to submit the relevant changes. Thanks in advance for contributing 😄

**Comment by alec-kr** [comment]
@irahorecka Please see the [ergast-refactor](https://github.com/alec-kr/F1PyStats/tree/ergast-refactor) branch of the repository for the changes I have made. This is the new code that you can work on.

**Comment by alec-kr** [comment]
@irahorecka Are you still working on this issue?

**Comment by irahorecka** [comment]
Hey there - sorry I got fairly busy this past week. I'm still interested. May I get an update on which branch to work?

**Comment by alec-kr** [comment]
Ah okay. All changes related to implementing classes and modules have already been merged to the main branch.

You can branch from main and work on that now
