### ISSUE TITLE
Migrate Codecov's GitHub App Integration

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#110]
We need to migrate Codecov's GitHub App Integration.

Quote from PR#109:
> 📣 This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None)

**Comment by alec-kr** [comment]
I actually set this up after I noticed that notification in the PR. Everything should be fine now.
