### ISSUE TITLE
Correct the author of this project

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#111]
The `authors` entry in `pyproject.toml` should contain @alec-kr .

**Comment by alec-kr** [comment]
Thanks for pointing that out. The current ```author``` is the contributor who added it to the repository. However, I never thought about replacing their name. 

You can add this into #112 if you'd like, or create a new PR.

**Comment by youpong** [comment]
@alec-kr, Please give me it in the format of `name <email>`.

**Comment by alec-kr** [comment]
Alec Ramdhan <akramdhan02@gmail.com>
