### ISSUE TITLE
Set up GitHub Pages

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#120]
## Description

Build a site like [this](https://youpong.github.io/cpp-sleep-sort/) on GitHub Pages to view the generated API documentation.

**Comment by alec-kr** [comment]
This is a great idea. I honestly never thought of implementing something like this before.

Should I assign the issue to you? It would be great to see a similar page for this repository in the future 😁

**Comment by youpong** [comment]
Yes. Please assign to me.

**Comment by youpong** [comment]
To build GitHub Pages, we need to perform two tasks.

1. Select Source of GitHub Pages.
2. Create a workflow to deploy.

Requiring administrative privileges, so i ask you to do that.

<img width="1149" alt="スクリーンショット 2023-03-14 11 19 57" src="https://user-images.githubusercontent.com/43817652/224876379-294dc473-5ac4-42ef-b0b7-23bf036ae882.png">

**Comment by alec-kr** [comment]
I have selected GitHub Actions

**Comment by youpong** [comment]
The workflow consists of two tasks. The building of the document and deploying to GitHub Pages.
The deploying was successful.
However, there are some problems with the building: the API Docs is not generated correctly.

I will continue to work on it and close this issue when it is resolved.

**Comment by alec-kr** [comment]
Okay great. Thanks for the update.

Good luck 💪🏽💯
