### ISSUE TITLE
Update noxfile.py

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#128]
## Description

Update noxfile.py to automate testing and generating documents.

- [x] generate docs
- [x] static check
- [x] lint
- [x] tests
- [x] code coverage

**Comment by alec-kr** [comment]
Do you plan to implement additional features related to this issue, or should this issue be closed?

**Comment by youpong** [comment]
There are about three more left: `lint`, `tests` and `code coverage`
