### ISSUE TITLE
Implement a function to return the lap times for a specified race

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#14]
A ```lap_times()``` function would be a great addition to the project. This function can probably accept parameters such as the year, race round, and lap number. Example: ```lap_times(year, round, lap_number)```

The output of the function can be a Pandas DataFrame containing each driver in the race, and their respective lap time.

**Comment by arungrace88** [comment]
Hello,
I was wondering if I could get involved and contribute to implementing the `lap_times()` function.? Thanks

**Comment by alec-kr** [comment]
Hey. Sure thing!

A sample API call can be found [here](http://ergast.com/api/f1/2011/5/laps/1), and the API documentation for this can be found at this [link](http://ergast.com/mrd/methods/laps/).

The function call should be somewhat similar to ```lap_times(year, round, lap_number)```, since the API needs all these parameters.

**Comment by Domefemia** [comment]
I'm trying to implent it but the only problem is that the argument used by this api it's different by the one used on the already implemented function to do that. To get the times I have already made a simple function called "get_driver_lap_time" instead.

**Comment by alec-kr** [comment]
> So what we do with the get_driver_names function?

Maybe we can create a function in the new file you are creating, called ```get_driver_id()```. I was expecting an issue like this to arise at some point during development, but I am unsure how we should handle this.

**Comment by alec-kr** [comment]
Update: By adding Object-Oriented programming principles, the issue of multiple functions with similar names should be resolved. 

Example: Instead of calling ```get_driver_names```, we will use something similar to ```lapTimes.get_driver_names()``` and ```raceWinners.get_driver_names()```

I have already started working on implementing classes and objects. I should be able to make a PR within the next few days.

**Comment by alec-kr** [comment]
I have just merged the branch that adds objects and classes to the code. Please have a look and let me know if you run into any issues while implementing the function.@arungrace88 @Domefemia

**Comment by alec-kr** [comment]
Great to hear you've made some progress @arungrace88.

Maybe you and @Domefemia can collaborate :)

**Comment by alec-kr** [comment]
@Domefemia since this issue was fixed by the first contributor, maybe you can have a look at #33.

**Comment by Domefemia** [comment]
Sorry if I don't answear on discussion, but my university year started, and I'm not that present on github
