### ISSUE TITLE
Function to get pit stops

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#33]
A pit_stops() function should be added to the package. This function can probably accept parameters such as the year, race round, and lap number. Example: ```pit_stops(year, round, lap_number)```

If ```lap_number``` is not provided, then the code should return all pit stops for the specific race.

The output of the function can be a Pandas DataFrame containing pit stop duration, time, lap number and driver name.

**Comment by Domefemia** [comment]
In which file are we gonna implement this function?

**Comment by alec-kr** [comment]
Hey. I've already done this in PR #35. I will merge the change later in the day.

**Comment by alec-kr** [comment]
@Domefemia I will be adding more issues next week. One of these issues should involve implementing a function capable of returning circuit information.

The reference page for this data can be found [here](https://ergast.com/mrd/methods/circuits/). If you'd like to work on something now, perhaps you can create an issue that involves developing a function ```get_circuits()``` that accepts race year as an optional parameter, and returns the list of circuits visited in that year. If the year is not provided, return all circuits used in F1 history.
