### ISSUE TITLE
Create get_constructors()

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#40]
This package should contain a function capable of returning constructor information such as team names and nationality. The reference page for this data can be found [here](https://ergast.com/mrd/methods/constructors/).

A function called ```get_constructors()``` may be created, that accepts a year as an optional parameter, and returns a DataFrame of participating constructors in that year, and their nationality. If the year is not provided, return all constructors in F1 history.

Example:
get_constructors(2022) -> Returns all constructors in 2022 and the nationalities
get_constructors() -> Returns all constructors in F1 history, and the nationalities

**Comment by dan-pavlov** [comment]
Hi there! I'd like to work on this issue, could you assign it to me?

**Comment by AdityaKeshan** [comment]
Could you assign this to me?

**Comment by alec-kr** [comment]
Hey there @dan-pavlov and @AdityaKeshan. Since Dan asked to work on the issue first, I feel it is the right thing to do by assigning the issue to him.

**Comment by alec-kr** [comment]
@AdityaKeshan I have just created issue #41. Feel free to have a look and let me know if you'd like to work on that instead :)

**Comment by alec-kr** [comment]
Hey @dan-pavlov. Can I get an update on your progress?

**Comment by dan-pavlov** [comment]
> Hey @dan-pavlov. Can I get an update on your progress?

Hey @alec-kr, of course, I'm still working on this, got caught up with work, but you'll have my complete pull request tomorrow :)

**Comment by alec-kr** [comment]
Great!

**Comment by dan-pavlov** [comment]
Hey @alec-kr, I've implemented the requested functionality and opened the following PR for it https://github.com/alec-kr/F1PyStats/pull/60

**Comment by alec-kr** [comment]
Great. Reviewing it now.
