### ISSUE TITLE
Add get_drivers() function

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#41]
A ```get_drivers()``` function would be a great addition to the project. This function can probably accept the year as a parameter, and race round can be an optional parameter. The function should return a DataFrame containing driver names, numbers, nationality and data of birth.

Example: 
- lap_times(year) -> Returns drivers that raced in a specified year
- lap_times(year, race_round) -> Returns drivers that raced in a particular race in a specified year

**Comment by Exoutia** [comment]
Can you assign it to me I am new to python, will try my best to do it.

**Comment by AdityaKeshan** [comment]
Can you assign to me?

**Comment by alec-kr** [comment]
I will be assigning this issue to @Exoutia since they have requested to work on this first. 

However, I have just created issue #42. I will assign issue #42 to contributors on a first come, first served basis @AdityaKeshan, @Antibodyy

**Comment by Exoutia** [comment]
So i have completed the get_drivers function

**Comment by alec-kr** [comment]
I've just reviewed it. Great work on the implementation. Just a few minor linting issues to correct, and it's ready to merge.
