### ISSUE TITLE
Develop finishing_status() function

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#42]
This package should contain a function capable of returning the finishing status of a race. The reference page for this data can be found [here](http://ergast.com/mrd/methods/status/).

A function called finishing_status() or similar may be created, that accepts a year, and returns a DataFrame with data similar to [this](http://ergast.com/api/f1/2010/status). The function should also accept race round as an optional parameter. If the race round is also provided, return the finishing status for the particular race (example API data [here](https://ergast.com/api/f1/2010/3/status))

Example:
finishing_status(2022) -> Returns finishing status for 2022. ([Example data](https://ergast.com/api/f1/2022/status))
finishing_status(2022, 3) -> Returns finishing status for the 3rd race in 2022. ([Example data](https://ergast.com/api/f1/2022/3/status))

**Comment by AdityaKeshan** [comment]
Please assign it to me

**Comment by achiverram28** [comment]
Please assign , I want to work on this

**Comment by alec-kr** [comment]
Issues are assigned to contributors on a first come, first served basis @AdityaKeshan @achiverram28. Since @AdityaKeshan has requested to work on it first, I will be assigning it to him.

**Comment by achiverram28** [comment]
can u create one more issue

**Comment by alec-kr** [comment]
@achiverram28 I have created issue #43. You can ask to be assigned before someone else does.

**Comment by AdityaKeshan** [comment]
Should I just make the function for a year and round in the f1pystats.py module or make a different altogether for all the functions call under the finishing status?

**Comment by alec-kr** [comment]
You should create a file called ```finishing_status.py``` or similar. In that file, create a class ```FinishingStatus```. The class will contain methods used to get the relevant data from the JSON data returned by the API. Example: ```get_statusId()```, ```get_status()```, ```get_count()```

Your new class should follow the same coding style as seen in all other classes such as [PitStops](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/pit_stops.py) and [DriverResults](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/driver_results.py)

See the function at [L186](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py#L186) of ```f1pystats.py``` to see how you can send optional parameters in a function (Note the use of the conditional statements from [L188 to 191](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py#L188-L191)). You should create a function similar to this in ```f1pystats.py```, and it should be named ```finishing_status()```.

**Comment by AdityaKeshan** [comment]
okay thanks
