### ISSUE TITLE
Add a qualifying_results() function

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#43]
A ```qualifying_results()``` function would be a great addition to the project. This function should accept year and race round as parameters. The function should return a DataFrame containing:

- qualifying position
- driver names
- driver numbers
- constructors
- qualifying times for Q1, Q2, and Q3.

The function should also accept an optional parameter ```pos```. This can be utilized to obtain qualifying results with a specific finishing position.

Example:

- ```qualifying_results(2022, 3)``` -> Returns qualifying results for the 3rd race in 2022 (API data [here](https://ergast.com/api/f1/2022/3/qualifying))
- ```lap_times(2022, pos=1)``` -> Returns drivers that got pole position in 2022 (API data [here](https://ergast.com/api/f1/2022/qualifying/1))

**Comment by achiverram28** [comment]
Yeah can you assign me this

**Comment by AlphaGaurav7** [comment]
Hey there! I can work on this issue and make the required functions, could you assign it to me?

**Comment by alec-kr** [comment]
@AlphaGaurav7 Issues are assigned on a first come first served basis. However, you can have a look at other issues in this repository and give them a go. If you submit a PR before the assigned individual, your changes may be merged :)

**Comment by achiverram28** [comment]
I have to create a class and add the method qualifying_results, could u just give an elaboration

**Comment by achiverram28** [comment]
I am currently following ur instruction as advised in the other issues

**Comment by alec-kr** [comment]
Create a class with the name ```QualifyingResults```, in a file with a name like ```qualifying_results.py```. The class will contain methods such as:
- ```get_positions```
- ```get_names```
- ```get_constructors```
- and all other relevant methods

Have a look at [```lap_times.py```](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/lap_times.py) to see how your file should be structured.

Don't forget to include your tests in the [/tests](https://github.com/alec-kr/F1PyStats/tree/main/tests) folder, along with sample data.

**Comment by alec-kr** [comment]
The ```qualifying_results``` function will be added in ```f1pystats.py```. In [this](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py) file, you can see how all other functions were implemented.

**Comment by achiverram28** [comment]
ok . sure

**Comment by achiverram28** [comment]
please check this pr, also inform if I also have to create the function in the https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py file

**Comment by achiverram28** [comment]
Yeah I have to , Ill do it now

**Comment by achiverram28** [comment]
I have done it please , look into it

**Comment by alec-kr** [comment]
Great work. I have reviewed and requested minor adjustments.

**Comment by achiverram28** [comment]
Please check it now
