### ISSUE TITLE
Add sprint qualifying results

### ISSUE THREAD

**Issue by AdityaKeshan** [alec-kr/F1PyStats#52]
Add Function ```sprint_qualifying_results()``` to return a DataFrame containing sprint race results which will take year and round as parameters.

**Comment by alec-kr** [comment]
Kindly provide more information on this issue.

- What is the problem/solution?
- How should this enhancement work?
- Should I assign this issue to you? Are you working on it?

**Comment by AdityaKeshan** [comment]
Add Function sprint_qualifying_results() to return Data Frame of Sprint Races which will take year and round as parameter. This will work as an enhancement. 

I would like to add this.

**Comment by alec-kr** [comment]
We should use ```sprint_results()``` instead of ```sprint_qualifying_results()```, since it is much shorter.

Please ensure your code contains an error handling mechanism to determine if a particular race round does not have a sprint race.

Example: ```sprint_results(2021, 5)``` should return something like : ```This Grand Prix did not have a sprint race```

**Comment by AdityaKeshan** [comment]
Hi, while adding it is showing this error
![image](https://user-images.githubusercontent.com/60391695/194188427-4b6a8dea-5576-4859-b3a1-e549c0f6c73f.png)

**Comment by alec-kr** [comment]
Not sure why you are getting this error. Perhaps try cloning the package in a different directory on your local system

**Comment by AdityaKeshan** [comment]
just after executing the poetry add command

**Comment by AdityaKeshan** [comment]
Tried in a different dir . Didnt work.

**Comment by alec-kr** [comment]
> poetry add

You must enter the F1PyStats directory, and run:

```poetry install```

**Comment by alec-kr** [comment]
Let me know if the issue still persists
