### ISSUE TITLE
Add code coverage to workflow

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#65]
## The Problem
Every time we write a new function and add tests, we have no idea how much of the source code is tested. This can potentially result in certain bugs in the code going unnoticed.

## Proposed Solution
To resolve this issue, a code coverage tool such as [coverage.py](https://github.com/nedbat/coveragepy) or similar, should be added to this repo's workflow.

The tool should run on every push/PR to the repo, and display the results.

The README should also include a label similar to the following, to illustrate the code coverage:
![image](https://user-images.githubusercontent.com/52685467/194732220-3325f65c-cfb8-439c-8324-6cc8e66932b4.png)

**Comment by rexdivakar** [comment]
Hey @alec-kr i can work on this part, pls assign it to my name

**Comment by alec-kr** [comment]
Assigned. Welcome aboard.

Be sure to keep me updated 😁

**Comment by alec-kr** [comment]
Can I get a progress update on your implementation? @rexdivakar

**Comment by rexdivakar** [comment]
Working on it will raise a pr asap

**Comment by alec-kr** [comment]
> Working on it 

You haven't forked the repo as yet ;)

**Comment by youpong** [comment]
I'll make a PR if this is ok.
https://app.codecov.io/gh/youpong/F1PyStats

**Comment by alec-kr** [comment]
@youpong The current assignee claims they are working on it, but they have not even forked the repo as yet.

I will assign it to you since you obviously did some great work here.

**Comment by alec-kr** [comment]
Please create a PR when ready

**Comment by youpong** [comment]
Sorry @rexdivakar. I may have wasted your time that you put into the research and coding. If you have any ideas to make code coverage better, please let us know.
