### ISSUE TITLE
[BUGFIX] Raise ValueError for incorrect years

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#68]
# Recommended Bug Fix

## The Problem
A nasty error is thrown when users enter an invalid year into certain functions such as ```get_drivers()``` and ``` get_constructors()```.

## The solution

A ```ValueError``` exception should be raised when the user enters an invalid year into ```get_drivers()``` and ```get_constructors()```. 

Examples:
* ```get_drivers(01)```
* ```get_constructors(3034)```
* ```get_drivers(1901)```

The above functions should return a ```ValueError```, stating that only values from 1950 to 2022 are considered valid years.

This same logic must be applied to ``` pit_stops``` , ``` finishing_status``` , and all other functions in the package. NOTE: Pit stop data is only available from 2012 onwards.

**Comment by Lakshayainani** [comment]
Hi @alec-kr,
Can it be assigned to me, will fix it.

**Comment by alec-kr** [comment]
Assigned!

**Comment by Lakshayainani** [comment]
@alec-kr can you please review and provide your comment on the fix, before merging it.
