### ISSUE TITLE
[BUGFIX] Fix typo in pit_stops()

### ISSUE THREAD

**Issue by alec-kr** [alec-kr/F1PyStats#74]
### Background
The ```pit_stops()``` function currently accepts 3 parameters: ```year```, ```race_round``` and ```stop_number```. If ```stop_number``` is not provided in the function call, all pit stops during the race should be returned.

### The issue
On [L198-L201](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py#L198-L201) of ```f1pystats.py```, the ```if``` statement checks if ```int == 0```, instead of checking if the value of ```stop_number == 0```.

This error is also highlighted in our [coverage reports](https://app.codecov.io/gh/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py), and it clearly shows that this line is not executed with our tests.

### Expected Changes
This is quite a simple fix: The issue should be resolved by replacing ```int == 0``` with ```stop_number == 0```.

**Comment by AtharvaDeshmukh0909** [comment]
can you assign this to me. Thank you
