### ISSUE TITLE
Add function to get fastest laps

### ISSUE THREAD

**Issue by Pana1v** [alec-kr/F1PyStats#76]
I want to add a method that generates the fastest lap, and the respective driver for a given race.

**Comment by alec-kr** [comment]
That's a great idea. I'll assign it to you.

**Comment by alec-kr** [comment]
Can you also get the lap time of the fastest lap? That should be a great addition.

**Comment by alec-kr** [comment]
Hey @Pana1v. Have you made any progress with the implementation?

**Comment by alec-kr** [comment]
Assignee has not responded within the past 48 hours, nor have they made any updates to their fork of the repository as of now. I will assume they are no longer working on the issue, and have them unassigned if they remain inactive.

**Comment by alec-kr** [comment]
Issue is now open to contributors

**Comment by mauro-fernandes** [comment]
I  think the fastest lap of a given race is one information, and the fastest laps of the race is another result (would it be the best lap of any driver, or would be the a list of all the laps of the race, one by one, with the respective driver). Anyway the respective driver would be an essential information linked to any given lap. Still, important be clear that the #number of the lap is one information, and the time of the lap would be another. Finally, It would be interesting also inform the constructor of each driver.

**Comment by alec-kr** [comment]
@mauro-fernandes This is a smart way to implement it. It  will require a bit more coding, and possibly include function calls to other parts of the API to get all the required data.

Would you like to work on the issue?

**Comment by mauro-fernandes** [comment]
I appreciate the consideration! 
Besides I am very confident coding in Python, actually I know little about the APIs either I'm still learning how to work with github, not so comfy. I feel able to do just one task at a time.

**Comment by alec-kr** [comment]
Great. Should I assign this issue to you?

You can create the function to get the fastest lap of the race, and the respective driver. Getting the fastest lap time also may be a "stretch goal".

**Comment by malay5** [comment]
Can you please assign the issue to me under hacktoberfest? I will write a function to get the fastest lap for the particular year and particular round, whcih can be called like 

fp.fastest_laps(year=2020,race_round=1)

**Comment by alec-kr** [comment]
Okay assigned. @malay5

**Comment by alec-kr** [comment]
Update: This issue has now been unassigned, due to inactivity of the author.

If anyone would like to make a follow-up PR on PR #91, and resolve the issue, then your help will be greatly appreciated.

**Comment by alec-kr** [comment]
@youpong Assigned!

**Comment by youpong** [comment]
I have referred to the existing code and noticed a behavior that seems to be a bug, so I will be issuing soon.

**Comment by alec-kr** [comment]
I have just merged the bugfix PR. Will you be working on this issue now? @youpong

**Comment by youpong** [comment]
Yes.
