### ISSUE TITLE
Extract the year which is the last ergast having info about

### ISSUE THREAD

**Issue by SilverTux** [alec-kr/F1PyStats#79]
**Describe the bug**
It would be good to have only one place where the code needs to be updated when new season data will be available.

**To Reproduce**
This is a code refactoring issue

**Expected behavior**
The behaviour of the code should be the same as before.

**Additional info**
f1pystats.py contains the year 2022 in lots of lines, those should be extracted.

**Comment by SilverTux** [comment]
I've started to do a PR for this, if you think this is not needed please let me know.

**Comment by alec-kr** [comment]
Hey @SilverTux. I've thought about this, but never really decided to implement it while I was developing those functions. (Procrastination is terrible)

> if you think this is not needed

Currently, we would have to update all 2022 values with 2023 when the new year starts. This change is needed, and would be the perfect solution.

By making this PR, you will enhance the tidiness of the code, and also reduce the time spent fixing issues like changing all values when the new year begins.
