### ISSUE TITLE
Add function to get fastest pit stop in a race

### ISSUE THREAD

**Issue by PawanPatil19** [alec-kr/F1PyStats#82]

**Comment by alec-kr** [comment]
Hey there. If you'd like to add this functionality, I would suggest adding an additional optional parameter to the current ```pit_stops``` function. (See [L218 of f1pystats.py](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/f1pystats.py#L218))

The new function call would be something like:

```
fp.pit_stops(year, race_round, stop_number, "fastest")
```

The "fastest" parameter will be optional, and should return the fastest pitstop of the race, or the fastest pitstop for a particular stop number (if stop_number is given as an argument).

If you have a different way of implementing this idea, please let me know, as I am also open to new solutions :)

**Comment by alec-kr** [comment]
Hey @dan-pavlov. Thank you for volunteering. I will assign the issue to you.

Please keep me updated, and let me know if you encounter any issues while developing the feature.
