### ISSUE TITLE
Installation steps lead to an error

### ISSUE THREAD

**Issue by nitrok** [alec-kr/F1PyStats#83]
**Describe the bug**
The steps described in the installation section of the [README.md](https://github.com/alec-kr/F1PyStats/blob/main/README.md) lead to an error

**To Reproduce**
1. Clone the repo
$ git clone https://github.com/alec-kr/F1PyStats.git

2. Install dependecies using poetry
$ cd ../F1PyStats
$ poetry install --only main

3. installation fails

```
➜  F1PyStats git:(main) poetry install

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)


  at ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
```
**Expected behavior**

**User System Specs (please complete the following information):**
 - OS: macOS 13.0 Beta (22A5358e)
 - Python: 3.10.0
 - Poetry  1.1.13

**Comment by alec-kr** [comment]
Looking into it now

**Comment by alec-kr** [comment]
This seems to be working fine for me. Are you sure you're in the project directory when running the install command?

Perhaps reinstalling Poetry may fix the problem. Please try that and let me know what happens.

**Comment by mathieu-lemay** [comment]
@nitrok You need to update poetry to 1.2.x (latest is 1.2.2.)

**Comment by alec-kr** [comment]
@mathieu-lemay Thank you for pointing this out. 

The author of this issue has added the minimum required Poetry version in the repo's README in #90 .
