### ISSUE TITLE
Update Python version in workflow

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#88]
**Is your feature request related to a problem? Please describe.**

Python 3.11.0 is released. So, change the python version used in workflow.

As is
[ "3.8", "3.9", "3.10"]

To be(draft)
["3.9", "3.10", "3.11"]

**Comment by alec-kr** [comment]
Should we include all 4 versions instead of just the latest 3 versions? Or is that not a good practice?

**Comment by youpong** [comment]
I think that limiting the Python versions supported would be advantageous in terms of development and maintenance costs.
I think it is sufficient to support the three most recent versions of Python.
What do you think?

**Comment by alec-kr** [comment]
Fair enough. We should go ahead with the 3 latest versions.
