### ISSUE TITLE
f1pystats.pit_stops() does not return the fastest time

### ISSUE THREAD

**Issue by youpong** [alec-kr/F1PyStats#94]
**Describe the bug**

f1pystats.pit_stops() does not return the fastest time.

**To Reproduce**

```
$ poetry run python
Python 3.10.7 (main, Oct  4 2022, 23:53:09) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import f1pystats as fp
>>> fp.pit_stops(2021, 2, 0, True)
   Driver Stop Lap      Time   Duration
0  stroll    2  32  15:58:13  24:52.090
```

**Expected behavior**

returns below.
```
   Driver Stop Lap      Time   Duration
0  giovinazzi    4  40  16:36:13  29.742
```
**Screenshots**
None.

**User System Specs (please complete the following information):**
 - OS:    Ubuntu 22.04.1 LTS
 - Python: 3.10.7

**Additional context**

None.

**Comment by alec-kr** [comment]
Should I assign you the issue?

**Comment by youpong** [comment]
Yes!
